name: omnisafe
channels:
  - conda-forge
  - defaults
dependencies:
  - appnope=0.1.4
  - asttokens=3.0.0
  - bzip2=1.0.8
  - ca-certificates=2025.1.31
  - comm=0.2.2
  - debugpy=1.8.13
  - decorator=5.2.1
  - exceptiongroup=1.2.2
  - executing=2.1.0
  - importlib-metadata=8.6.1
  - ipykernel=6.29.5
  - ipython=8.34.0
  - jedi=0.19.2
  - jupyter_client=8.6.3
  - jupyter_core=5.7.2
  - krb5=1.21.3
  - libcxx=20.1.2
  - libedit=3.1.20250104
  - libffi=3.4.6
  - liblzma=5.6.4
  - libsodium=1.0.20
  - libsqlite=3.49.1
  - libzlib=1.3.1
  - matplotlib-inline=0.1.7
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - openssl=3.4.1
  - packaging=24.2
  - parso=0.8.4
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pip=25.0.1
  - platformdirs=4.3.7
  - prompt-toolkit=3.0.50
  - psutil=7.0.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pygments=2.19.1
  - python=3.10.16
  - python-dateutil=2.9.0.post0
  - python_abi=3.10
  - pyzmq=26.3.0
  - readline=8.2
  - six=1.17.0
  - stack_data=0.6.3
  - tk=8.6.13
  - tornado=6.4.2
  - traitlets=5.14.3
  - typing_extensions=4.13.0
  - wcwidth=0.2.13
  - wheel=0.45.1
  - zeromq=4.3.5
  - zipp=3.21.0
  - pip:
      - absl-py==2.2.1
      - annotated-types==0.7.0
      - beautifulsoup4==4.13.3
      - certifi==2025.1.31
      - charset-normalizer==3.4.1
      - click==8.1.8
      - cloudpickle==3.1.1
      - contourpy==1.3.1
      - cycler==0.12.1
      - docker-pycreds==0.4.0
      - farama-notifications==0.0.4
      - filelock==3.18.0
      - fonttools==4.56.0
      - fsspec==2025.3.2
      - gdown==5.2.0
      - gitdb==4.0.12
      - gitpython==3.1.44
      - glfw==2.8.0
      - grpcio==1.71.0
      - gymnasium==0.28.1
      - idna==3.10
      - imageio==2.37.0
      - imageio-ffmpeg==0.6.0
      - jax-jumpy==1.0.0
      - jinja2==3.1.6
      - kiwisolver==1.4.8
      - markdown==3.7
      - markdown-it-py==3.0.0
      - markupsafe==3.0.2
      - matplotlib==3.10.1
      - mdurl==0.1.2
      - moviepy==2.1.2
      - mpmath==1.3.0
      - mujoco==2.3.0
      - networkx==3.4.2
      - numpy==1.23.5
      - omnisafe==0.5.0
      - pandas==2.0.3
      - pillow==10.4.0
      - proglog==0.1.11
      - protobuf==5.29.4
      - pydantic==2.11.1
      - pydantic-core==2.33.0
      - pygame==2.1.0
      - pyopengl==3.1.9
      - pyparsing==3.2.3
      - pysocks==1.7.1
      - python-dotenv==1.1.0
      - pytz==2025.2
      - pyyaml==6.0.2
      - requests==2.32.3
      - rich==14.0.0
      - safety-gymnasium==0.4.1
      - seaborn==0.13.2
      - sentry-sdk==2.25.0
      - setproctitle==1.3.5
      - setuptools==78.1.0
      - shellingham==1.5.4
      - smmap==5.0.2
      - soupsieve==2.6
      - sympy==1.13.1
      - tensorboard==2.19.0
      - tensorboard-data-server==0.7.2
      - torch==2.6.0
      - tqdm==4.67.1
      - typer==0.15.2
      - typing-inspection==0.4.0
      - tzdata==2025.2
      - urllib3==2.3.0
      - wandb==0.19.9
      - werkzeug==3.1.3
      - xmltodict==0.14.2
